apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: nikhil-harshil
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/nikhil-harshil"