apiVersion: v1
kind: Service
metadata:
  labels:
    app: pages
    tier: database
  name: pages-mysql
  namespace: nikhil-harshil
spec:
  ports:
    - port: 3306
  selector:
    app: pages
    tier: database
  type: NodePort