apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-nh
  namespace: nikhil-harshil
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/nikhil-harshil"