apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-nh
  namespace: nikhil-harshil
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi